<a href="https://colab.research.google.com/github/meisam210905/Sani/blob/main/MNIST_Random_Forest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import datasets

In [2]:
data = datasets.load_digits()

In [3]:
X = data.images.reshape((len(data.images), -1))

In [4]:
y = data.target

In [5]:
from sklearn.ensemble import RandomForestClassifier

In [6]:
rfc_clf = RandomForestClassifier()
rfc_clf.fit(X[:1000], y[:1000])

RandomForestClassifier()

In [7]:
from sklearn import metrics

In [9]:
p = rfc_clf.predict(X[1000:]) 
e = y[1000:]
print(metrics.classification_report(e, p))

              precision    recall  f1-score   support

           0       0.97      0.99      0.98        79
           1       0.96      0.88      0.92        80
           2       1.00      0.91      0.95        77
           3       0.89      0.82      0.86        79
           4       0.98      0.95      0.96        83
           5       0.87      0.99      0.93        82
           6       0.99      1.00      0.99        80
           7       0.92      0.99      0.95        80
           8       0.92      0.88      0.90        76
           9       0.84      0.90      0.87        81

    accuracy                           0.93       797
   macro avg       0.93      0.93      0.93       797
weighted avg       0.93      0.93      0.93       797



In [10]:
print(metrics.confusion_matrix(e, p))

[[78  0  0  0  1  0  0  0  0  0]
 [ 0 70  0  1  0  1  0  0  0  8]
 [ 1  0 70  4  0  0  0  0  0  2]
 [ 0  1  0 65  0  4  0  4  4  1]
 [ 0  0  0  0 79  0  0  2  0  2]
 [ 0  0  0  0  0 81  1  0  0  0]
 [ 0  0  0  0  0  0 80  0  0  0]
 [ 0  0  0  0  0  0  0 79  1  0]
 [ 0  2  0  0  1  4  0  1 67  1]
 [ 1  0  0  3  0  3  0  0  1 73]]
