<a href="https://colab.research.google.com/github/meisam210905/Sani/blob/main/MNIST_KNN_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import datasets

In [2]:
data = datasets.load_digits()

In [3]:
X = data.images.reshape((len(data.images), -1))
len(X)

1797

In [4]:
y = data.target
len(y)

1797

In [5]:
from sklearn.neighbors import KNeighborsClassifier

In [15]:
from sklearn import metrics

In [31]:
knn_clf = KNeighborsClassifier(n_neighbors=5)
knn_clf.fit(X[:1000], y[:1000])
p = knn_clf.predict(X[1000:]) 
e = y[1000:]
print(metrics.classification_report(e, p))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99        79
           1       0.95      0.97      0.96        80
           2       0.97      0.94      0.95        77
           3       0.91      0.90      0.90        79
           4       1.00      0.95      0.98        83
           5       0.94      0.99      0.96        82
           6       0.99      1.00      0.99        80
           7       0.94      1.00      0.97        80
           8       0.95      0.91      0.93        76
           9       0.94      0.91      0.92        81

    accuracy                           0.96       797
   macro avg       0.96      0.96      0.96       797
weighted avg       0.96      0.96      0.96       797



In [17]:
print(metrics.confusion_matrix(e, p))

[[79  0  0  0  0  0  0  0  0  0]
 [ 0 78  0  0  0  0  0  0  1  1]
 [ 1  0 72  4  0  0  0  0  0  0]
 [ 0  0  1 71  0  2  0  3  2  0]
 [ 0  0  0  0 79  0  0  1  0  3]
 [ 0  0  0  0  0 81  1  0  0  0]
 [ 0  0  0  0  0  0 80  0  0  0]
 [ 0  0  0  0  0  0  0 80  0  0]
 [ 0  4  1  0  0  0  0  1 69  1]
 [ 0  0  0  3  0  3  0  0  1 74]]
